"""
Type stubs for the zerokv._core C extension module (built via nanobind).

This file serves as the definitive Python API reference.
The actual _core extension is compiled from src/python/bindings.cpp.
"""

from __future__ import annotations

import enum
from typing import Any, Callable, Optional, Tuple, Union, overload

import numpy as np

try:
    import cupy as cp
    GpuArray = cp.ndarray
except ImportError:
    GpuArray = Any  # type: ignore[misc]

BufferLike = Union[bytes, bytearray, memoryview, np.ndarray, GpuArray]

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

TAG_ANY: int
TAG_MASK_ALL: int
TAG_MASK_USER: int

def make_tag(context_id: int, user_tag: int) -> int: ...
def tag_context(tag: int) -> int: ...
def tag_user(tag: int) -> int: ...

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class MemoryType(enum.IntEnum):
    HOST = 0
    CUDA = 1
    ROCM = 2
    ASCEND = 3

class ErrorCode(enum.IntEnum):
    SUCCESS = 0
    IN_PROGRESS = 1
    CANCELED = 2
    TIMEOUT = 3
    CONNECTION_REFUSED = 100
    CONNECTION_RESET = 101
    ENDPOINT_CLOSED = 102
    TRANSPORT_ERROR = 200
    MESSAGE_TRUNCATED = 201
    TAG_MISMATCH = 202
    OUT_OF_MEMORY = 300
    INVALID_BUFFER = 301
    REGISTRATION_FAILED = 302
    PLUGIN_NOT_FOUND = 400
    PLUGIN_INIT_FAILED = 401
    INVALID_ARGUMENT = 900
    NOT_IMPLEMENTED = 901
    INTERNAL_ERROR = 999

class SubscriptionEventType(enum.IntEnum):
    PUBLISHED = 0
    UPDATED = 1
    UNPUBLISHED = 2
    OWNER_LOST = 3

# ---------------------------------------------------------------------------
# Exceptions / status
# ---------------------------------------------------------------------------

class AXONError(Exception):
    code: ErrorCode
    message: str

class Status:
    def __init__(self, code: ErrorCode = ErrorCode.SUCCESS, message: str = "") -> None: ...
    def ok(self) -> bool: ...
    def in_progress(self) -> bool: ...
    def throw_if_error(self) -> None: ...
    @property
    def code(self) -> ErrorCode: ...
    @property
    def message(self) -> str: ...
    def __bool__(self) -> bool: ...

# ---------------------------------------------------------------------------
# Futures
# ---------------------------------------------------------------------------

class FutureVoid:
    def ready(self) -> bool: ...
    def get(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def status(self) -> Status: ...

class FutureSize:
    def ready(self) -> bool: ...
    def get(self) -> int: ...
    def cancel(self) -> None: ...
    @property
    def status(self) -> Status: ...

class FutureRecv:
    def ready(self) -> bool: ...
    def get(self) -> Tuple[int, int]: ...
    def cancel(self) -> None: ...
    @property
    def status(self) -> Status: ...

class FutureU64:
    def ready(self) -> bool: ...
    def get(self) -> int: ...
    def cancel(self) -> None: ...
    @property
    def status(self) -> Status: ...

class FutureEndpoint:
    def ready(self) -> bool: ...
    def get(self) -> Endpoint: ...
    def cancel(self) -> None: ...
    @property
    def status(self) -> Status: ...

class FutureFetch:
    def ready(self) -> bool: ...
    def get(self) -> FetchResult: ...
    def cancel(self) -> None: ...
    @property
    def status(self) -> Status: ...

# ---------------------------------------------------------------------------
# MemoryRegion
# ---------------------------------------------------------------------------

class MemoryRegion:
    @staticmethod
    def register_(
        ctx: Context,
        buffer: BufferLike,
        memory_type: MemoryType = MemoryType.HOST,
    ) -> MemoryRegion: ...

    @staticmethod
    def allocate(
        ctx: Context,
        size: int,
        memory_type: MemoryType = MemoryType.HOST,
    ) -> MemoryRegion: ...

    @property
    def address(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def memory_type(self) -> MemoryType: ...
    @property
    def remote_key(self) -> bytes: ...
    def __len__(self) -> int: ...
    def to_numpy(self) -> np.ndarray: ...

# ---------------------------------------------------------------------------
# Config / Context
# ---------------------------------------------------------------------------

class Config:
    def __init__(
        self,
        *,
        transport: str = "ucx",
        num_workers: int = 0,
        memory_pool_size: int = 64 * 1024 * 1024,
        max_inflight_requests: int = 1024,
        connect_timeout: float = 10.0,
        registration_cache: bool = True,
        registration_cache_max_entries: int = 0,
    ) -> None: ...

    @property
    def transport(self) -> str: ...
    @property
    def num_workers(self) -> int: ...
    @property
    def memory_pool_size(self) -> int: ...
    def get(self, key: str, default: str = "") -> str: ...

class Context:
    @overload
    def __init__(self, *, config: Config) -> None: ...
    @overload
    def __init__(
        self,
        *,
        transport: Optional[str] = ...,
        num_workers: Optional[int] = ...,
        memory_pool_size: Optional[int] = ...,
    ) -> None: ...

    def create_worker(self, index: int = 0) -> Worker: ...
    def supports_memory_type(self, mt: MemoryType) -> bool: ...
    def supports_rma(self) -> bool: ...
    def supports_hw_tag_matching(self) -> bool: ...
    @property
    def config(self) -> Config: ...

# ---------------------------------------------------------------------------
# Transport
# ---------------------------------------------------------------------------

class Endpoint:
    def tag_send(self, buffer: BufferLike, tag: int) -> FutureVoid: ...
    def tag_send_region(self, region: MemoryRegion, tag: int) -> FutureVoid: ...
    def tag_recv(self, buffer: BufferLike, tag: int, tag_mask: int = TAG_MASK_ALL) -> FutureRecv: ...

    def put(
        self,
        local: BufferLike | MemoryRegion,
        remote_address: int,
        remote_key: bytes,
    ) -> FutureVoid: ...

    def get(
        self,
        local: BufferLike | MemoryRegion,
        remote_address: int,
        remote_key: bytes,
    ) -> FutureVoid: ...

    def flush(self) -> FutureVoid: ...
    def close(self) -> FutureVoid: ...
    @property
    def is_connected(self) -> bool: ...

class Listener:
    @property
    def address(self) -> str: ...
    def close(self) -> FutureVoid: ...

class Worker:
    async def connect(self, address: str) -> Endpoint: ...
    def listen(self, address: str, on_accept: Callable[[Endpoint], None]) -> Listener: ...
    def attach_to_event_loop(self) -> None: ...
    def detach_from_event_loop(self) -> None: ...

# ---------------------------------------------------------------------------
# KV API
# ---------------------------------------------------------------------------

class KeyInfo:
    @property
    def key(self) -> str: ...
    @property
    def owner_node_id(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def is_deleted(self) -> bool: ...

class FetchResult:
    @property
    def data(self) -> bytes: ...
    @property
    def owner_node_id(self) -> str: ...
    @property
    def version(self) -> int: ...

class PublishMetrics:
    @property
    def total_us(self) -> int: ...
    @property
    def prepare_region_us(self) -> int: ...
    @property
    def pack_rkey_us(self) -> int: ...
    @property
    def put_meta_rpc_us(self) -> int: ...

class FetchMetrics:
    @property
    def total_us(self) -> int: ...
    @property
    def get_meta_rpc_us(self) -> int: ...
    @property
    def peer_connect_us(self) -> int: ...
    @property
    def rdma_prepare_us(self) -> int: ...
    @property
    def rdma_get_us(self) -> int: ...

class PushMetrics:
    @property
    def total_us(self) -> int: ...
    @property
    def accept_us(self) -> int: ...
    @property
    def prepare_region_us(self) -> int: ...
    @property
    def pack_rkey_us(self) -> int: ...
    @property
    def rpc_us(self) -> int: ...

class SubscriptionEvent:
    @property
    def type(self) -> SubscriptionEventType: ...
    @property
    def key(self) -> str: ...
    @property
    def owner_node_id(self) -> str: ...
    @property
    def version(self) -> int: ...

class KVServer:
    def __init__(self, config: Optional[Config] = None) -> None: ...
    def start(self, address: str) -> Status: ...
    def stop(self) -> Status: ...
    @property
    def address(self) -> str: ...

class KVNode:
    def __init__(self, config: Optional[Config] = None) -> None: ...
    def start(self, server_address: str, data_address: str, node_id: str) -> Status: ...
    def stop(self) -> Status: ...
    @property
    def node_id(self) -> str: ...
    def publish(self, key: str, value: BufferLike) -> FutureVoid: ...
    def fetch(self, key: str) -> FutureFetch: ...
    def push(self, key: str, value: BufferLike) -> FutureVoid: ...
    def subscribe(self, key: str) -> FutureVoid: ...
    def unsubscribe(self, key: str) -> FutureVoid: ...
    def drain_subscription_events(self) -> list[SubscriptionEvent]: ...
    def last_publish_metrics(self) -> Optional[PublishMetrics]: ...
    def last_fetch_metrics(self) -> Optional[FetchMetrics]: ...
    def last_push_metrics(self) -> Optional[PushMetrics]: ...
